POST http://localhost:3000/register/client
Content-Type: application/json

{
  "nombre": "Juan",
  "correo": "juan.perez@example.com",
  "contrasena": "123456",
  "numeroTelefono": 123456789,
  "placa": "ABC123",
  "marca": "Toyota",
  "modelo": "Corolla",
  "tipo": "Sedán"
}
